### ISSUE TITLE
Require admin approval for signup

### ISSUE THREAD

**Issue by Rhendox** [oofdere/jebat#40]
Signing up for jebat should require administrator approval, we don't want any randoms gaining access to the database and posting/taking potentially dangerous files. We could make an admin control panel page or send an email/text/discord to facilitate this.

**Comment by oofdere** [comment]
Already implemented via #5, controlled via the roles page. Roles for new users can be controlled using the following variables in the `.env` file.

```ini
# default permissions for new users
IS_ADMIN=True
CAN_VIEW=True
CAN_UPLOAD=True
```

This means that while anyone can sign up, you can make them have zero access to any of the content using the `$CAN_VIEW` variable.

**Comment by Rhendox** [comment]
I guess that's a solution? We can definitely make it better, so I guess this is now just a feature request and not an issue.

**Comment by oofdere** [comment]
Make it better how? Any specific suggestions?

**Comment by oofdere** [comment]
#42?
